-- Generated by `pnpm puzzles:build` from puzzles/. Do not edit.
--
-- The puzzle catalog that race rounds pick from. Reference fixes are left out
-- on purpose: they never go in the database. Safe to run again: adds new
-- puzzles, updates changed ones and retires the ones no longer in puzzles/
-- (kept for old rounds, never picked again).
--
-- Local: the seed file, applied by `pnpm db:reset`. Live: run in the
-- Supabase SQL Editor after migration 20261008000006, and again whenever
-- puzzles/ changes.

insert into public.puzzles
  (id, language, level, title, description, buggy_code, tests, hint, time_limit_seconds, base_points)
values
  (
    'average-rating',
    'javascript',
    'easy',
    'Average rating',
    'averageRating(ratings) is the average of the star ratings. A review that was left without a rating is null and must be ignored, not counted. No ratings at all gives 0.',
    '// Average of the ratings, ignoring unrated reviews (null).
function averageRating(ratings) {
  let total = 0;
  let count = 0;
  for (const rating of ratings) {
    if (rating === null) continue;
    total += rating;
    count += 1;
  }
  if (count === 0) return 0;
  return total / ratings.length;
}
',
    'test("averages plain ratings", () => {
  expect(averageRating([4, 5, 3])).toBe(4);
});
test("ignores unrated reviews", () => {
  expect(averageRating([5, null, 3, null])).toBe(4);
});
test("a single rating is its own average", () => {
  expect(averageRating([2])).toBe(2);
});
test("no ratings gives 0", () => {
  expect(averageRating([])).toBe(0);
  expect(averageRating([null, null])).toBe(0);
});
',
    'Compare what you add up with what you divide by.',
    180,
    100
  ),
  (
    'clamp-score',
    'javascript',
    'easy',
    'Clamp a score',
    'clampScore(score, min, max) keeps a score inside the range min to max (both included). A score below min becomes min, a score above max becomes max, anything else is returned unchanged.',
    '// Keeps a score between `min` and `max`, both included.
function clampScore(score, min, max) {
  if (score < min) return max;
  if (score > max) return max;
  return score;
}
',
    'test("keeps a score inside the range", () => {
  expect(clampScore(50, 0, 100)).toBe(50);
});
test("raises a score that is too low", () => {
  expect(clampScore(-5, 0, 100)).toBe(0);
});
test("lowers a score that is too high", () => {
  expect(clampScore(140, 0, 100)).toBe(100);
});
test("keeps the limits themselves", () => {
  expect(clampScore(0, 0, 100)).toBe(0);
  expect(clampScore(100, 0, 100)).toBe(100);
});
',
    'Look at which limit each branch hands back.',
    180,
    100
  ),
  (
    'sum-of-evens',
    'javascript',
    'easy',
    'Sum of evens',
    'sumOfEvens(nums) returns the sum of every even number in the array. An empty array sums to 0.',
    '// Returns the sum of the even numbers in `nums`.
function sumOfEvens(nums) {
  let total = 0;
  for (let i = 1; i < nums.length; i++) {
    if (nums[i] % 2 === 0) {
      total += nums[i];
    }
  }
  return total;
}
',
    'test("adds the even numbers", () => {
  expect(sumOfEvens([1, 2, 3, 4])).toBe(6);
});
test("counts the first element", () => {
  expect(sumOfEvens([2, 4, 6])).toBe(12);
});
test("handles negative numbers", () => {
  expect(sumOfEvens([-2, 3])).toBe(-2);
});
test("returns 0 for an empty array", () => {
  expect(sumOfEvens([])).toBe(0);
});
',
    'Check which elements the loop actually visits.',
    180,
    100
  ),
  (
    'title-case',
    'javascript',
    'easy',
    'Title case',
    'titleCase(sentence) capitalises the first letter of every word and lowercases the rest. Words are separated by single spaces. An empty string stays empty.',
    '// Capitalises every word: "hELLO wORLD" -> "Hello World".
function titleCase(sentence) {
  const words = sentence.split(" ");
  const result = [];
  for (let i = 0; i < words.length - 1; i++) {
    const word = words[i];
    result.push(word.charAt(0).toUpperCase() + word.slice(1).toLowerCase());
  }
  return result.join(" ");
}
',
    'test("capitalises two words", () => {
  expect(titleCase("hello world")).toBe("Hello World");
});
test("capitalises a single word", () => {
  expect(titleCase("bug")).toBe("Bug");
});
test("lowercases the rest of each word", () => {
  expect(titleCase("mIxEd cAsE words")).toBe("Mixed Case Words");
});
test("keeps an empty string empty", () => {
  expect(titleCase("")).toBe("");
});
',
    'Count how many words the loop actually visits.',
    180,
    100
  ),
  (
    'top-scores',
    'javascript',
    'easy',
    'Top scores',
    'topScores(scores, limit) returns the best `limit` scores, highest first. The original array must stay exactly as it was.',
    '// Returns the best `limit` scores, highest first. Does not change `scores`.
function topScores(scores, limit) {
  const sorted = [...scores];
  sorted.sort();
  return sorted.slice(0, limit);
}
',
    'test("returns the highest scores first", () => {
  expect(topScores([5, 40, 100, 9], 3)).toEqual([100, 40, 9]);
});
test("returns everything when limit is large", () => {
  expect(topScores([3, 1, 2], 10)).toEqual([3, 2, 1]);
});
test("does not change the original array", () => {
  const scores = [5, 40, 100, 9];
  topScores(scores, 2);
  expect(scores).toEqual([5, 40, 100, 9]);
});
test("handles an empty list", () => {
  expect(topScores([], 3)).toEqual([]);
});
',
    'What does sort() do when you give it no comparison function?',
    180,
    100
  ),
  (
    'apply-discount',
    'javascript',
    'medium',
    'Apply a discount',
    'applyDiscount(items, category, percent) returns a NEW list where every item in the category is `percent` percent cheaper (price in cents, rounded to a whole cent). Other items are unchanged. The original items must not be modified.',
    '// Returns a new list; items in `category` get `percent` percent off.
// Prices are in cents and are rounded to a whole cent.
// The original items must not change.
function applyDiscount(items, category, percent) {
  return items.map((item) => {
    if (item.category !== category) return item;
    const discounted = Math.round(item.price * (1 - percent / 100));
    item.price = discounted;
    return item;
  });
}

// Total price of all items, in cents.
function totalPrice(items) {
  return items.reduce((sum, item) => sum + item.price, 0);
}

// Formats cents as dollars, e.g. 1999 -> "$19.99".
function formatPrice(cents) {
  return "$" + (cents / 100).toFixed(2);
}
',
    'const catalog = [
  { name: "Novel", category: "books", price: 2000 },
  { name: "Pen", category: "office", price: 500 },
  { name: "Atlas", category: "books", price: 4000 },
];

test("discounts items in the category", () => {
  const result = applyDiscount(catalog, "books", 25);
  expect(result.map((item) => item.price)).toEqual([1500, 500, 3000]);
});
test("leaves other categories alone", () => {
  expect(applyDiscount(catalog, "toys", 50)).toEqual(catalog);
});
test("does not change the original items", () => {
  applyDiscount(catalog, "books", 25);
  expect(catalog[0].price).toBe(2000);
  expect(catalog[2].price).toBe(4000);
});
test("totals and formats the result", () => {
  const total = totalPrice(applyDiscount(catalog, "office", 10));
  expect(formatPrice(total)).toBe("$64.50");
});
',
    'Does the original list still look the same after the call?',
    300,
    200
  ),
  (
    'format-date',
    'javascript',
    'medium',
    'Format a date',
    'formatDate(iso) turns an ISO timestamp into "DD/MM/YYYY" using UTC, so the result never depends on the machine''s time zone. For example "2024-03-05T23:30:00Z" becomes "05/03/2024". formatTimeline(list) formats a list of timestamps, oldest first.',
    '// Formats an ISO timestamp as "DD/MM/YYYY" in UTC, e.g.
// "2024-03-05T23:30:00Z" -> "05/03/2024". UTC keeps the result the same on
// every machine, whatever its time zone.
function formatDate(iso) {
  const date = new Date(iso);
  const day = String(date.getUTCDate());
  const month = String(date.getUTCMonth()).padStart(2, "0");
  const year = date.getUTCFullYear();
  return `${day}/${month}/${year}`;
}

// Formats a list of ISO timestamps, oldest first. Does not change the list.
function formatTimeline(isoList) {
  return [...isoList]
    .sort((a, b) => new Date(a) - new Date(b))
    .map((iso) => formatDate(iso));
}
',
    'test("formats a late evening UTC timestamp", () => {
  expect(formatDate("2024-03-05T23:30:00Z")).toBe("05/03/2024");
});
test("formats a date with a two digit day and month", () => {
  expect(formatDate("2023-12-25T08:00:00Z")).toBe("25/12/2023");
});
test("uses UTC, not the local time zone", () => {
  expect(formatDate("2024-01-01T00:00:00Z")).toBe("01/01/2024");
});
test("formats a timeline oldest first", () => {
  expect(
    formatTimeline(["2024-02-10T00:00:00Z", "2023-11-30T12:00:00Z"]),
  ).toEqual(["30/11/2023", "10/02/2024"]);
});
',
    'Check both the day and the month of "2024-03-05" by hand.',
    300,
    200
  ),
  (
    'make-adders',
    'javascript',
    'medium',
    'Make adders',
    'makeAdders(amounts) returns one function per amount; each function adds its own amount to the number it is given. sumSteps(amounts, start) applies them one after another, so sumSteps([1, 5], 10) is 16.',
    '// Builds one function per amount.
// makeAdders([1, 5]) -> [(x) => x + 1, (x) => x + 5]
function makeAdders(amounts) {
  const adders = [];
  for (var i = 0; i < amounts.length; i++) {
    adders.push((x) => x + amounts[i]);
  }
  return adders;
}

// Runs a number through every function in order.
function pipe(fns, start) {
  let value = start;
  for (const fn of fns) value = fn(value);
  return value;
}

// Adds each amount in turn: sumSteps([1, 5], 10) -> 16.
function sumSteps(amounts, start) {
  return pipe(makeAdders(amounts), start);
}
',
    'test("each adder uses its own amount", () => {
  const [addOne, addFive] = makeAdders([1, 5]);
  expect(addOne(10)).toBe(11);
  expect(addFive(10)).toBe(15);
});
test("builds one function per amount", () => {
  expect(makeAdders([3, 4, 5]).length).toBe(3);
});
test("sumSteps applies the adders in order", () => {
  expect(sumSteps([1, 5], 10)).toBe(16);
});
test("no amounts leaves the number alone", () => {
  expect(sumSteps([], 7)).toBe(7);
});
',
    'Every function created in the loop shares one variable. When do they read it?',
    300,
    200
  ),
  (
    'retry-until-success',
    'javascript',
    'medium',
    'Retry until success',
    'retry(task, options) calls the async task until it succeeds, at most `attempts` times, waiting `delayMs` between tries and calling onRetry(error, attempt) before each retry. It resolves with the first success or rejects with the last error.',
    '// Waits `ms` milliseconds.
function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// Calls `task(attempt)` until it succeeds, at most `attempts` times in total,
// waiting `delayMs` between tries. Calls `onRetry(error, attempt)` after each
// failed try that will be retried. Resolves with the first successful result,
// or rejects with the last error when every try fails.
async function retry(task, { attempts = 3, delayMs = 0, onRetry } = {}) {
  let lastError;
  for (let attempt = 1; attempt <= attempts; attempt++) {
    try {
      return task(attempt);
    } catch (error) {
      lastError = error;
      if (attempt < attempts) {
        if (onRetry) onRetry(error, attempt);
        await wait(delayMs);
      }
    }
  }
  throw lastError;
}
',
    'function flaky(failures) {
  let calls = 0;
  return async (attempt) => {
    calls += 1;
    if (calls <= failures) throw new Error(`fail ${attempt}`);
    return `ok on ${attempt}`;
  };
}

async function errorFrom(promise) {
  try {
    await promise;
  } catch (error) {
    return error.message;
  }
  return "no error";
}

test("resolves on the first try", async () => {
  expect(await retry(flaky(0))).toBe("ok on 1");
});
test("retries a rejected task", async () => {
  expect(await retry(flaky(2), { attempts: 3 })).toBe("ok on 3");
});
test("rejects with the last error", async () => {
  expect(await errorFrom(retry(flaky(5), { attempts: 3 }))).toBe("fail 3");
});
test("reports each retry", async () => {
  const seen = [];
  await retry(flaky(2), {
    onRetry: (error, n) => seen.push([error.message, n]),
  });
  expect(seen).toEqual([
    ["fail 1", 1],
    ["fail 2", 2],
  ]);
});
test("retries a task that throws synchronously", async () => {
  let calls = 0;
  const task = () => {
    calls += 1;
    if (calls === 1) throw new Error("sync");
    return "done";
  };
  expect(await retry(task)).toBe("done");
});
',
    'A try/catch only catches a rejected promise if something waits for it.',
    300,
    200
  ),
  (
    'sum-fields',
    'javascript',
    'medium',
    'Sum form fields',
    'Form inputs arrive as strings. sumFields(values) adds up the filled-in fields (blank ones are skipped) and returns the total rounded to 2 decimal places. averageField(values) is the average of the filled-in fields, or 0 when all are blank.',
    '// Adds up the filled-in fields (blank ones are skipped), rounded to 2 decimals.
function sumFields(values) {
  let total = 0;
  for (const value of values) {
    if (value.trim() === "") continue;
    total += parseInt(value, 10);
  }
  return Math.round(total * 100) / 100;
}

// Number of fields that were filled in.
function countFilled(values) {
  return values.filter((value) => value.trim() !== "").length;
}

// Average of the filled-in fields, or 0 when all of them are blank.
function averageField(values) {
  const filled = countFilled(values);
  return filled === 0 ? 0 : sumFields(values) / filled;
}
',
    'test("adds whole numbers", () => {
  expect(sumFields(["10", "20", "5"])).toBe(35);
});
test("adds decimals", () => {
  expect(sumFields(["1.5", "2.25"])).toBe(3.75);
});
test("skips blank fields", () => {
  expect(sumFields(["4", "", "  ", "6"])).toBe(10);
});
test("rounds away floating point noise", () => {
  expect(sumFields(["0.1", "0.2"])).toBe(0.3);
});
test("averages only the filled fields", () => {
  expect(averageField(["1.5", "", "2.5"])).toBe(2);
  expect(averageField(["", " "])).toBe(0);
});
',
    'What happens to "2.5" when it is read as a whole number?',
    300,
    200
  ),
  (
    'inventory-reducer',
    'javascript',
    'hard',
    'Inventory reducer',
    'reduce(state, action) returns a NEW state and never changes the old one. State is { stock: { [sku]: number }, log: string[] }. "receive" adds to the stock, "ship" removes stock (shipping exactly what is left is fine; shipping more throws "not enough <sku>"), and "discontinue" removes a sku that has no stock left.',
    '// A tiny inventory store. State shape:
//   { stock: { [sku]: number }, log: string[] }
// reduce(state, action) must return a NEW state and never change the old one.
//
// Actions:
//   { type: "receive", sku, qty }  adds qty to the stock of sku
//   { type: "ship", sku, qty }     removes qty; throws if there is not enough
//   { type: "discontinue", sku }   removes a sku that has no stock left

const initialState = { stock: {}, log: [] };

function reduce(state, action) {
  switch (action.type) {
    case "receive": {
      const current = state.stock[action.sku] ?? 0;
      return {
        ...state,
        stock: Object.assign(state.stock, {
          [action.sku]: current + action.qty,
        }),
        log: [...state.log, `received ${action.qty} ${action.sku}`],
      };
    }
    case "ship": {
      const current = state.stock[action.sku] ?? 0;
      if (action.qty >= current) throw new Error(`not enough ${action.sku}`);
      return {
        ...state,
        stock: { ...state.stock, [action.sku]: current - action.qty },
        log: [...state.log, `shipped ${action.qty} ${action.sku}`],
      };
    }
    case "discontinue": {
      if ((state.stock[action.sku] ?? 0) !== 0) {
        throw new Error(`${action.sku} still has stock`);
      }
      delete state.stock[action.sku];
      const stock = state.stock;
      return {
        ...state,
        stock,
        log: [...state.log, `discontinued ${action.sku}`],
      };
    }
    default:
      return state;
  }
}

// Applies a list of actions, starting from an empty inventory.
function replay(actions) {
  return actions.reduce(reduce, initialState);
}

// Total number of units in stock.
function totalUnits(state) {
  return Object.values(state.stock).reduce((sum, qty) => sum + qty, 0);
}
',
    'function snapshot(state) {
  return JSON.stringify(state);
}

test("receiving adds to the stock and the log", () => {
  const state = replay([
    { type: "receive", sku: "pen", qty: 5 },
    { type: "receive", sku: "pen", qty: 3 },
  ]);
  expect(state.stock).toEqual({ pen: 8 });
  expect(state.log).toEqual(["received 5 pen", "received 3 pen"]);
});
test("receiving does not change the previous state", () => {
  const before = replay([{ type: "receive", sku: "pen", qty: 5 }]);
  const saved = snapshot(before);
  reduce(before, { type: "receive", sku: "ink", qty: 2 });
  expect(snapshot(before)).toBe(saved);
  expect(snapshot(initialState)).toBe(''{"stock":{},"log":[]}'');
});
test("shipping everything that is left is allowed", () => {
  const state = replay([
    { type: "receive", sku: "pen", qty: 4 },
    { type: "ship", sku: "pen", qty: 4 },
  ]);
  expect(totalUnits(state)).toBe(0);
});
test("shipping more than the stock throws", () => {
  const before = replay([{ type: "receive", sku: "pen", qty: 4 }]);
  expect(() => reduce(before, { type: "ship", sku: "pen", qty: 5 })).toThrow(
    "not enough pen",
  );
});
test("discontinuing removes the sku without touching the old state", () => {
  const before = replay([
    { type: "receive", sku: "pen", qty: 1 },
    { type: "ship", sku: "pen", qty: 1 },
  ]);
  const saved = snapshot(before);
  const after = reduce(before, { type: "discontinue", sku: "pen" });
  expect(after.stock).toEqual({});
  expect(snapshot(before)).toBe(saved);
});
test("a sku with stock cannot be discontinued", () => {
  const before = replay([{ type: "receive", sku: "pen", qty: 2 }]);
  expect(() => reduce(before, { type: "discontinue", sku: "pen" })).toThrow(
    "still has stock",
  );
});
',
    'Compare the old state before and after each action. Which actions change it, and which comparison is too strict?',
    480,
    300
  ),
  (
    'leaderboard',
    'javascript',
    'hard',
    'Quiz leaderboard',
    'Entries look like { name, points, time }. They are ranked by more points first, then by the faster (smaller) time, then by name A to Z. Entries with the same points AND the same time share a rank, and the next rank skips ahead (1, 1, 3). sortEntries returns a sorted copy and must not reorder the original array.',
    '// Leaderboard for a quiz night.
// Each entry is { name, points, time } where time is the seconds taken.
//
// Ranking rules:
//   1. more points first
//   2. on equal points, the faster time first
//   3. on equal points and time, alphabetical by name
// Entries that tie on points AND time share one rank (1, 1, 3, ...).

function compareEntries(a, b) {
  if (a.points !== b.points) return a.points - b.points;
  if (a.time !== b.time) return a.time - b.time;
  return a.name.localeCompare(b.name);
}

// Returns a sorted copy of the entries, best first.
function sortEntries(entries) {
  return entries.sort(compareEntries);
}

// Adds a `rank` to every entry of an already sorted list.
function rankEntries(sorted) {
  const ranked = [];
  for (let i = 0; i < sorted.length; i++) {
    const entry = sorted[i];
    const previous = ranked[i - 1];
    const tied =
      previous !== undefined &&
      previous.points === entry.points &&
      previous.time === entry.time;
    ranked.push({ ...entry, rank: tied ? previous.rank : i });
  }
  return ranked;
}

// The names of the best `n` entries, best first.
function podium(entries, n = 3) {
  return rankEntries(sortEntries(entries))
    .slice(0, n)
    .map((entry) => entry.name);
}

// One printable line per entry: "1. Ada - 90 pts (42s)".
function formatBoard(entries) {
  return rankEntries(sortEntries(entries)).map(
    (entry) =>
      `${entry.rank}. ${entry.name} - ${entry.points} pts (${entry.time}s)`,
  );
}

// Name of the entry in last place, or null for an empty board.
function lastPlace(entries) {
  const sorted = sortEntries(entries);
  return sorted.length === 0 ? null : sorted[sorted.length - 1].name;
}
',
    'const quiz = [
  { name: "Cy", points: 70, time: 50 },
  { name: "Ada", points: 90, time: 60 },
  { name: "Bo", points: 90, time: 45 },
  { name: "Dee", points: 70, time: 50 },
];

test("more points rank higher", () => {
  expect(sortEntries(quiz).map((entry) => entry.name)).toEqual([
    "Bo",
    "Ada",
    "Cy",
    "Dee",
  ]);
});
test("equal points are decided by the faster time", () => {
  const board = [
    { name: "Slow", points: 10, time: 90 },
    { name: "Fast", points: 10, time: 20 },
  ];
  expect(podium(board)).toEqual(["Fast", "Slow"]);
});
test("sorting does not reorder the original array", () => {
  const board = quiz.map((entry) => ({ ...entry }));
  sortEntries(board);
  expect(board.map((entry) => entry.name)).toEqual(["Cy", "Ada", "Bo", "Dee"]);
});
test("ranks start at 1 and ties share a rank", () => {
  expect(formatBoard(quiz)).toEqual([
    "1. Bo - 90 pts (45s)",
    "2. Ada - 90 pts (60s)",
    "3. Cy - 70 pts (50s)",
    "3. Dee - 70 pts (50s)",
  ]);
});
test("the rank after a tie skips ahead", () => {
  const board = [
    { name: "A", points: 5, time: 1 },
    { name: "B", points: 5, time: 1 },
    { name: "C", points: 3, time: 1 },
  ];
  expect(rankEntries(sortEntries(board)).map((entry) => entry.rank)).toEqual([
    1, 1, 3,
  ]);
});
test("finds the last place", () => {
  expect(lastPlace(quiz)).toBe("Dee");
  expect(lastPlace([])).toBe(null);
});
',
    'Three small slips, in the comparison, the copy and the rank numbers. Try a tiny board first.',
    480,
    300
  ),
  (
    'lru-cache',
    'javascript',
    'hard',
    'LRU cache',
    'LruCache(capacity) remembers at most `capacity` entries. get and set both count as "using" a key. When the cache is full, setting a NEW key throws out the least recently used one. Setting a key that already exists never evicts anything. keys() lists the keys from least to most recently used; has and peek do not count as use.',
    '// A small least-recently-used cache.
// `get` and `set` both count as "use"; `has` and `peek` do not.
// When the cache is full, setting a NEW key evicts the least recently used one.
// Setting a key that already exists replaces its value and never evicts.
class LruCache {
  constructor(capacity) {
    if (!Number.isInteger(capacity) || capacity < 1) {
      throw new Error("capacity must be a positive whole number");
    }
    this.capacity = capacity;
    this.entries = new Map();
  }

  get size() {
    return this.entries.size;
  }

  has(key) {
    return this.entries.has(key);
  }

  // Reads a value without counting as use.
  peek(key) {
    return this.entries.get(key);
  }

  get(key) {
    if (!this.entries.has(key)) return undefined;
    const value = this.entries.get(key);
    return value;
  }

  set(key, value) {
    if (this.entries.size > this.capacity) {
      const oldest = this.entries.keys().next().value;
      this.entries.delete(oldest);
    }
    this.entries.set(key, value);
  }

  // Keys from least to most recently used.
  keys() {
    return [...this.entries.keys()];
  }

  clear() {
    this.entries.clear();
  }
}

// Wraps `fn` so repeated calls with the same argument reuse the cached result.
function memoize(fn, capacity) {
  const cache = new LruCache(capacity);
  return (arg) => {
    if (cache.has(arg)) return cache.get(arg);
    const result = fn(arg);
    cache.set(arg, result);
    return result;
  };
}
',
    'function filled() {
  const cache = new LruCache(3);
  cache.set("a", 1);
  cache.set("b", 2);
  cache.set("c", 3);
  return cache;
}

test("stores and reads values", () => {
  const cache = filled();
  expect(cache.get("b")).toBe(2);
  expect(cache.get("zzz")).toBe(undefined);
  expect(cache.size).toBe(3);
});
test("evicts the oldest key when a new key does not fit", () => {
  const cache = filled();
  cache.set("d", 4);
  expect(cache.keys()).toEqual(["b", "c", "d"]);
  expect(cache.size).toBe(3);
});
test("reading a key makes it the most recently used", () => {
  const cache = filled();
  cache.get("a");
  cache.set("d", 4);
  expect(cache.keys()).toEqual(["c", "a", "d"]);
});
test("setting an existing key never evicts and moves it to the back", () => {
  const cache = filled();
  cache.set("b", 20);
  expect(cache.keys()).toEqual(["a", "c", "b"]);
  expect(cache.peek("b")).toBe(20);
});
test("peek and has do not count as use", () => {
  const cache = filled();
  cache.peek("a");
  cache.has("a");
  expect(cache.keys()).toEqual(["a", "b", "c"]);
});
test("memoize computes each argument once", () => {
  let calls = 0;
  const square = memoize((n) => {
    calls += 1;
    return n * n;
  }, 2);
  expect(square(3)).toBe(9);
  expect(square(3)).toBe(9);
  expect(calls).toBe(1);
});
',
    'Follow the order of keys() after each call. Who moves to the back, and when is anything evicted?',
    480,
    300
  ),
  (
    'user-loader',
    'javascript',
    'hard',
    'User loader',
    'loadUser adds the number of PUBLISHED posts (draft is false) to a user. loadUsers loads many users in parallel and keeps the order of the ids. A user that does not exist (the error code is "NOT_FOUND") is left out. Any other error must reject the whole call.',
    '// Loads user profiles through an API client with two async methods:
//   api.getUser(id)   -> { id, name }   (rejects with error.code "NOT_FOUND")
//   api.getPosts(id)  -> [{ title, draft }]
//
// The helpers below never talk to the network themselves; they only combine
// what the client returns.

// One user plus the number of published (non-draft) posts.
async function loadUser(api, id) {
  const [user, posts] = await Promise.all([api.getUser(id), api.getPosts(id)]);
  const published = posts;
  return { ...user, postCount: published.length };
}

// Loads many users in parallel and keeps the order of `ids`.
// Unknown users (NOT_FOUND) are left out; any other error rejects the call.
async function loadUsers(api, ids) {
  const loaded = await Promise.all(
    ids.map(async (id) => {
      try {
        return loadUser(api, id);
      } catch (error) {
        return null;
      }
    }),
  );
  return loaded.filter((user) => user !== null);
}

// Names of all found users as one comma separated string.
async function userNames(api, ids) {
  const users = await loadUsers(api, ids);
  return users.map((user) => user.name).join(", ");
}

// The found user with the most published posts, or null when nobody is found.
// On a tie the user listed first wins.
async function mostActiveUser(api, ids) {
  const users = await loadUsers(api, ids);
  let best = null;
  for (const user of users) {
    if (best === null || user.postCount > best.postCount) best = user;
  }
  return best;
}

// How many of the given ids belong to real users.
async function countFound(api, ids) {
  const users = await loadUsers(api, ids);
  return users.length;
}
',
    'const database = {
  1: {
    name: "Ada",
    posts: [{ draft: false }, { draft: false }, { draft: true }],
  },
  2: { name: "Bo", posts: [{ draft: false }] },
  3: { name: "Cy", posts: [{ draft: true }, { draft: true }] },
  9: { name: "Broken", broken: true, posts: [] },
};

const api = {
  async getUser(id) {
    const row = database[id];
    if (!row) {
      const error = new Error(`no user ${id}`);
      error.code = "NOT_FOUND";
      throw error;
    }
    if (row.broken) throw new Error("database is down");
    return { id, name: row.name };
  },
  async getPosts(id) {
    return database[id] ? database[id].posts : [];
  },
};

async function errorFrom(promise) {
  try {
    await promise;
  } catch (error) {
    return error.message;
  }
  return "no error";
}

test("counts only published posts", async () => {
  expect(await loadUser(api, 1)).toEqual({ id: 1, name: "Ada", postCount: 2 });
  expect((await loadUser(api, 3)).postCount).toBe(0);
});
test("loads users in the order of the ids", async () => {
  expect(await userNames(api, [2, 1, 3])).toBe("Bo, Ada, Cy");
});
test("leaves out users that do not exist", async () => {
  expect(await userNames(api, [1, 404, 2])).toBe("Ada, Bo");
  expect(await countFound(api, [404, 405])).toBe(0);
});
test("any other error rejects the whole call", async () => {
  expect(await errorFrom(loadUsers(api, [1, 9, 2]))).toBe("database is down");
});
test("finds the most active user", async () => {
  expect((await mostActiveUser(api, [2, 1, 3])).name).toBe("Ada");
  expect(await mostActiveUser(api, [404])).toBe(null);
});
',
    'Think about what a try/catch really catches around a promise, and what the catch block lets through.',
    480,
    300
  ),
  (
    'word-stats',
    'javascript',
    'hard',
    'Word statistics',
    'tokenize splits text into lowercase words (letters and apostrophes, case does not matter). countWords counts them, topWords gives the n most common as [word, count] (equal counts in alphabetical order) and averageLength is the mean word length rounded to the nearest tenth.',
    '// Word statistics for a piece of text.
// Words are made of letters and apostrophes; everything else separates them.
// Case does not matter: "The" and "the" are the same word, kept in lowercase.

function tokenize(text) {
  const matches = text.match(/[A-Za-z'']+/g);
  return matches ?? [];
}

// Counts how many times each word appears, as an object word -> count.
function countWords(words) {
  const counts = Object.create(null);
  for (const word of words) {
    counts[word] = (counts[word] || 0) + 1;
  }
  return counts;
}

// The `n` most common words as [word, count] pairs, most common first.
// Words with the same count are in alphabetical order.
function topWords(counts, n) {
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, n);
}

// Mean word length rounded to the nearest tenth; 0 when there are no words.
function averageLength(words) {
  if (words.length === 0) return 0;
  const letters = words.reduce((sum, word) => sum + word.length, 0);
  return Math.floor((letters / words.length) * 10) / 10;
}

// Everything at once.
function summarize(text, n = 3) {
  const words = tokenize(text);
  const counts = countWords(words);
  return {
    total: words.length,
    unique: Object.keys(counts).length,
    top: topWords(counts, n),
    averageLength: averageLength(words),
  };
}

// The words that appear exactly once, in the order they first appear.
function singletons(text) {
  const words = tokenize(text);
  const counts = countWords(words);
  return [...new Set(words)].filter((word) => counts[word] === 1);
}
',
    'test("splits words and ignores punctuation", () => {
  expect(tokenize("Hello, world! It''s 5 o''clock.")).toEqual([
    "hello",
    "world",
    "it''s",
    "o''clock",
  ]);
});
test("treats upper and lower case as the same word", () => {
  const counts = countWords(tokenize("The cat and THE hat"));
  expect(counts.the).toBe(2);
});
test("counts words that look like object properties", () => {
  const counts = countWords(tokenize("constructor the constructor"));
  expect(counts.constructor).toBe(2);
  expect(counts.the).toBe(1);
});
test("breaks ties alphabetically", () => {
  const top = topWords(
    countWords(tokenize("pear apple pear fig apple kiwi")),
    3,
  );
  expect(top).toEqual([
    ["apple", 2],
    ["pear", 2],
    ["fig", 1],
  ]);
});
test("rounds the average length to the nearest tenth", () => {
  expect(averageLength(["abcd", "abcde"])).toBe(4.5);
  expect(averageLength(["abc", "abc", "abc", "abcd"])).toBe(3.3);
});
test("lists the words used only once", () => {
  expect(singletons("a b a c")).toEqual(["b", "c"]);
});
',
    'Try the word "The", a tie in counts, and an average that ends in .x5.',
    480,
    300
  ),
  (
    'add-tag',
    'python',
    'easy',
    'Add a tag',
    'add_tag(tag, tags) appends the tag to the given list and returns that list. The list is optional: when no list is given, it starts a new empty one, so separate calls never share tags.',
    'def add_tag(tag, tags=[]):
    """Add `tag` to `tags` and return it.

    Without a list, start a new one.
    """
    tags.append(tag)
    return tags
',
    'def test_adds_to_a_given_list():
    assert add_tag("b", ["a"]) == ["a", "b"]


def test_returns_the_same_list():
    tags = ["a"]
    assert add_tag("b", tags) is tags


def test_first_call_without_a_list():
    assert add_tag("x") == ["x"]


def test_separate_calls_do_not_share_tags():
    add_tag("first")
    assert add_tag("second") == ["second"]
',
    'When does Python create a default argument value?',
    180,
    100
  ),
  (
    'average',
    'python',
    'easy',
    'Average',
    'average(numbers) returns the mean of a list of numbers, including the decimal part (average([1, 2]) is 1.5). An empty list gives 0.',
    'def average(numbers):
    """Mean of a list of numbers; an empty list gives 0."""
    if not numbers:
        return 0
    total = sum(numbers)
    return total // len(numbers)
',
    'def test_whole_average():
    assert average([2, 4, 6]) == 4


def test_keeps_the_decimal_part():
    assert average([1, 2]) == 1.5


def test_single_number():
    assert average([7]) == 7


def test_empty_list_is_zero():
    assert average([]) == 0
',
    'Python has two kinds of division. Which one keeps the decimals?',
    180,
    100
  ),
  (
    'cheapest-items',
    'python',
    'easy',
    'Cheapest items',
    'cheapest(prices, count) returns the count lowest prices, lowest first. If there are fewer prices than count, it returns all of them sorted. The original list must not be changed.',
    'def cheapest(prices, count):
    """The `count` lowest prices, lowest first.

    The original list is left as it was.
    """
    ordered = prices.sort()
    return ordered[:count]
',
    'def test_returns_lowest_prices_first():
    assert cheapest([30, 10, 20, 40], 2) == [10, 20]


def test_count_larger_than_list():
    assert cheapest([5, 3], 5) == [3, 5]


def test_original_list_is_unchanged():
    prices = [9, 1, 5]
    cheapest(prices, 2)
    assert prices == [9, 1, 5]


def test_zero_items():
    assert cheapest([4, 2], 0) == []
',
    'What does list.sort() give back?',
    180,
    100
  ),
  (
    'is-palindrome',
    'python',
    'easy',
    'Palindrome',
    'is_palindrome(text) is True when the text reads the same backwards, ignoring spaces and upper or lower case. "Never odd or even" is a palindrome.',
    'def is_palindrome(text):
    """True if `text` reads the same backwards, ignoring case and spaces."""
    cleaned = text.replace(" ", "")
    backwards = cleaned[::-1]
    return cleaned == backwards
',
    'def test_simple_palindrome():
    assert is_palindrome("level")


def test_not_a_palindrome():
    assert not is_palindrome("python")


def test_ignores_spaces():
    assert is_palindrome("nurses run")


def test_ignores_case():
    assert is_palindrome("Never odd or even")
',
    'Are "A" and "a" the same letter for the == operator?',
    180,
    100
  ),
  (
    'sum-to',
    'python',
    'easy',
    'Sum to n',
    'sum_to(n) adds up the whole numbers from 1 to n, including n. sum_to(4) is 10. For n of 0 the sum is 0.',
    'def sum_to(n):
    """Add up the whole numbers from 1 to n, including n. sum_to(4) is 10."""
    total = 0
    for number in range(1, n):
        total += number
    return total
',
    'def test_small_sum():
    assert sum_to(4) == 10


def test_one():
    assert sum_to(1) == 1


def test_ten():
    assert sum_to(10) == 55


def test_zero_is_zero():
    assert sum_to(0) == 0
',
    'What is the last number range(1, n) gives you?',
    180,
    100
  ),
  (
    'letter-grade',
    'python',
    'medium',
    'Letter grades',
    'letter_grade(score) turns a score from 0 to 100 into a letter - 90 and up is A, 80 and up is B, 70 and up is C, 60 and up is D, anything lower is F. A score outside 0 to 100 raises ValueError. class_summary counts how many of each letter there are.',
    'GRADES = [(90, "A"), (80, "B"), (70, "C"), (60, "D")]


def letter_grade(score):
    """Letter for a score from 0 to 100.

    90 and up is A, 80 and up is B, 70 and up is C, 60 and up is D, and
    anything lower is F. A score outside 0-100 raises ValueError.
    """
    if score < 0 or score > 100:
        raise ValueError("score must be between 0 and 100")
    for minimum, letter in GRADES:
        if score > minimum:
            return letter
    return "F"


def class_summary(scores):
    """Count of each letter grade, e.g. {"A": 2, "C": 1}."""
    summary = {}
    for score in scores:
        letter = letter_grade(score)
        summary[letter] = summary.get(letter, 0) + 1
    return summary
',
    'def test_clear_grades():
    assert letter_grade(95) == "A"
    assert letter_grade(75) == "C"
    assert letter_grade(30) == "F"


def test_the_limit_itself_gets_the_higher_letter():
    assert letter_grade(90) == "A"
    assert letter_grade(60) == "D"


def test_just_below_a_limit():
    assert letter_grade(89) == "B"


def test_scores_outside_the_range_are_rejected():
    for bad in (-1, 101):
        try:
            letter_grade(bad)
        except ValueError:
            continue
        raise AssertionError("expected ValueError for %s" % bad)


def test_class_summary_counts_letters():
    assert class_summary([100, 85, 90, 40, 82]) == {"A": 2, "B": 2, "F": 1}
',
    'What should a score of exactly 90 get? Check the comparison against each limit.',
    300,
    200
  ),
  (
    'new-board',
    'python',
    'medium',
    'Game board',
    'new_board(rows, cols) creates a grid of 0s where every cell can be changed on its own. place(board, row, col, mark) puts a mark in one cell, count_marks counts how many cells hold a mark, and is_full says whether no 0 is left.',
    'def new_board(rows, cols):
    """A rows x cols grid filled with 0. Every cell is independent."""
    return [[0] * cols] * rows


def place(board, row, col, mark):
    """Put `mark` in one cell and return the board."""
    board[row][col] = mark
    return board


def count_marks(board, mark):
    """How many cells hold `mark`."""
    return sum(row.count(mark) for row in board)


def is_full(board):
    """True when no cell is still 0."""
    return all(cell != 0 for row in board for cell in row)


def rows_with(board, mark):
    """Row numbers (counting from 0) that hold `mark`."""
    return [index for index, row in enumerate(board) if mark in row]
',
    'def test_new_board_is_all_zeros():
    assert new_board(2, 3) == [[0, 0, 0], [0, 0, 0]]


def test_placing_changes_one_cell():
    board = place(new_board(3, 3), 1, 1, "X")
    assert board == [[0, 0, 0], [0, "X", 0], [0, 0, 0]]


def test_counts_marks():
    board = new_board(2, 2)
    place(board, 0, 0, "O")
    place(board, 1, 1, "O")
    assert count_marks(board, "O") == 2


def test_full_board():
    board = new_board(2, 2)
    assert not is_full(board)
    for row in range(2):
        for col in range(2):
            place(board, row, col, "X")
    assert is_full(board)
',
    'After placing one mark, how many cells hold it? Look at how the rows are created.',
    300,
    200
  ),
  (
    'percent-done',
    'python',
    'medium',
    'Percent done',
    'percent_done(done, total) is the share of finished tasks as a whole percentage, and halves round UP (1 of 8 is 12.5 so it shows 13). No tasks at all counts as 0 percent. progress_label turns it into text like "50% done (4/8)".',
    'import math


def percent_done(done, total):
    """Whole-number percentage of finished tasks.

    Halves round up: 1 of 8 is 12.5, which shows as 13.
    No tasks at all counts as 0 percent.
    """
    return round(done * 100 / total)


def progress_label(done, total):
    """Text such as "50% done (4/8)"."""
    return "%d%% done (%d/%d)" % (percent_done(done, total), done, total)


def is_complete(done, total):
    """True when every task is done and there is at least one task."""
    return total > 0 and done >= total


def tasks_left(done, total):
    """How many tasks are still open (never below 0)."""
    return max(total - done, 0)


def is_started(done):
    """True when at least one task is done."""
    return done > 0
',
    'def test_plain_percentages():
    assert percent_done(4, 8) == 50
    assert percent_done(8, 8) == 100


def test_rounds_to_the_nearest_whole_number():
    assert percent_done(1, 3) == 33
    assert percent_done(2, 3) == 67


def test_halves_round_up():
    assert percent_done(1, 8) == 13
    assert percent_done(5, 8) == 63


def test_no_tasks_is_zero_percent():
    assert percent_done(0, 0) == 0
    assert progress_label(0, 0) == "0% done (0/0)"


def test_label_and_completion():
    assert progress_label(4, 8) == "50% done (4/8)"
    assert is_complete(3, 3)
    assert not is_complete(0, 0)
',
    'Try 1 of 8 and 0 of 0. What does round() do with 12.5?',
    300,
    200
  ),
  (
    'positive-stats',
    'python',
    'medium',
    'Positive stats',
    'describe(values) returns (lowest, highest, average) of the values greater than zero, and None when there are none. describe([4, -1, 2, 6]) is (2, 6, 4.0). spread(values) is highest minus lowest, or 0 when there are no positive values.',
    'def positive_values(values):
    """The values greater than zero, in order."""
    return (value for value in values if value > 0)


def describe(values):
    """Lowest, highest and average of the positive values.

    describe([4, -1, 2, 6]) is (2, 6, 4.0).
    With no positive values it returns None.
    """
    positives = positive_values(values)
    if not positives:
        return None
    lowest = min(positives)
    highest = max(positives)
    average = sum(positives) / len(positives)
    return (lowest, highest, average)


def spread(values):
    """Highest minus lowest positive value, or 0 if there are none."""
    stats = describe(values)
    if stats is None:
        return 0
    return stats[1] - stats[0]
',
    'def test_positive_values_keeps_order():
    assert list(positive_values([3, -2, 0, 7])) == [3, 7]


def test_describe_mixed_values():
    assert describe([4, -1, 2, 6]) == (2, 6, 4.0)


def test_describe_single_value():
    assert describe([5]) == (5, 5, 5.0)


def test_no_positive_values():
    assert describe([-1, 0]) is None
    assert describe([]) is None


def test_spread():
    assert spread([4, -1, 2, 6]) == 4
    assert spread([-3]) == 0
',
    'Can you loop over a generator a second time?',
    300,
    200
  ),
  (
    'remove-negatives',
    'python',
    'medium',
    'Remove negatives',
    'remove_negatives(numbers) removes every negative number from the list IN PLACE and returns how many were removed. average_without_negatives gives the mean of the non-negative numbers (0 if none) and must not change the list it is given.',
    'def remove_negatives(numbers):
    """Remove every negative number from the list, in place.

    Returns how many numbers were removed.
    """
    removed = 0
    for number in numbers:
        if number < 0:
            numbers.remove(number)
            removed += 1
    return removed


def average_without_negatives(numbers):
    """Mean of the non-negative numbers (0 if there are none).

    The list that is passed in is not changed.
    """
    kept = list(numbers)
    remove_negatives(kept)
    return sum(kept) / len(kept) if kept else 0


def count_negatives(numbers):
    """How many numbers are below zero."""
    return sum(1 for number in numbers if number < 0)
',
    'def test_removes_a_negative():
    numbers = [3, -1, 4]
    assert remove_negatives(numbers) == 1
    assert numbers == [3, 4]


def test_removes_neighbouring_negatives():
    numbers = [-1, -2, -3, 5]
    assert remove_negatives(numbers) == 3
    assert numbers == [5]


def test_nothing_to_remove():
    numbers = [1, 2]
    assert remove_negatives(numbers) == 0
    assert numbers == [1, 2]


def test_average_ignores_negatives_and_keeps_the_input():
    numbers = [2, -5, 4, -1]
    assert average_without_negatives(numbers) == 3
    assert numbers == [2, -5, 4, -1]
    assert count_negatives(numbers) == 2
',
    'What happens to the loop when you remove items from the list it is walking over?',
    300,
    200
  ),
  (
    'add-months',
    'python',
    'hard',
    'Monthly dates',
    'add_months(day, months) moves a date by whole months; if the day does not exist in the new month it uses the last day of that month (Jan 31 plus 1 month is Feb 28, or Feb 29 in a leap year). billing_dates(start, count) lists monthly billing dates counted from the START date, so Jan 31 gives Jan 31, Feb 28, Mar 31. age_in_years only counts a birthday once it has been reached.',
    'import calendar
from datetime import date


def month_name(month):
    """English name of a month number (1-12)."""
    return calendar.month_name[month]


def days_in_month(year, month):
    """Number of days in the given month (month is 1-12)."""
    return calendar.monthrange(year, month)[1]


def add_months(day, months):
    """Move a date by whole months.

    If the day does not exist in the new month, the last day of that month is
    used: Jan 31 + 1 month is Feb 28 (Feb 29 in a leap year).
    """
    index = day.year * 12 + (day.month) + months
    year = index // 12
    month = index % 12 + 1
    new_day = day.day
    return date(year, month, new_day)


def billing_dates(start, count):
    """The first `count` monthly billing dates, starting with `start`.

    Every date is worked out from `start`, so the day is never lost:
    Jan 31 gives Jan 31, Feb 28, Mar 31, Apr 30, ...
    """
    dates = []
    current = start
    for _ in range(count):
        dates.append(current)
        current = add_months(current, 1)
    return dates


def last_day_of_month(day):
    """The last date of the month that `day` is in."""
    return date(day.year, day.month, days_in_month(day.year, day.month))


def is_month_end(day):
    """True when `day` is the last day of its month."""
    return day == last_day_of_month(day)


def days_until(today, target):
    """Whole days from `today` to `target` (negative if it is in the past)."""
    return (target - today).days


def age_in_years(born, today):
    """Whole years between `born` and `today`.

    A birthday that has not been reached yet this year does not count.
    """
    years = today.year - born.year
    if (today.month, today.day) < (born.month, born.day):
        years -= 1
    return years
',
    'def test_adds_months_within_a_year():
    assert add_months(date(2024, 3, 15), 2) == date(2024, 5, 15)


def test_wraps_over_the_new_year():
    assert add_months(date(2024, 11, 10), 3) == date(2025, 2, 10)
    assert add_months(date(2024, 12, 5), 1) == date(2025, 1, 5)


def test_goes_back_in_time():
    assert add_months(date(2024, 1, 20), -2) == date(2023, 11, 20)


def test_short_months_use_their_last_day():
    assert add_months(date(2023, 1, 31), 1) == date(2023, 2, 28)
    assert add_months(date(2024, 1, 31), 1) == date(2024, 2, 29)


def test_billing_dates_are_counted_from_the_start():
    assert billing_dates(date(2023, 1, 31), 4) == [
        date(2023, 1, 31),
        date(2023, 2, 28),
        date(2023, 3, 31),
        date(2023, 4, 30),
    ]


def test_age_waits_for_the_birthday():
    born = date(2000, 6, 15)
    assert age_in_years(born, date(2024, 6, 14)) == 23
    assert age_in_years(born, date(2024, 6, 15)) == 24
',
    'Check the month number maths, the shortest months, and whether each billing date is computed from the start or from the previous date.',
    480,
    300
  ),
  (
    'merge-intervals',
    'python',
    'hard',
    'Merge intervals',
    'merge_intervals(intervals) merges overlapping or touching [start, end] intervals - [[1, 3], [2, 6], [8, 10], [6, 7]] becomes [[1, 7], [8, 10]]. The input list and the intervals inside it must not change. free_slots uses it to list the gaps in a day that no interval covers.',
    'def merge_intervals(intervals):
    """Merge overlapping or touching [start, end] intervals.

    merge_intervals([[1, 3], [2, 6], [8, 10], [6, 7]]) -> [[1, 7], [8, 10]]
    The input list and the intervals inside it must not change.
    """
    if not intervals:
        return []
    ordered = list(intervals)
    merged = [list(ordered[0])]
    for start, end in ordered[1:]:
        last = merged[-1]
        if start < last[1]:
            last[1] = end
        else:
            merged.append([start, end])
    return merged


def total_covered(intervals):
    """Total length covered by the intervals (overlaps count once)."""
    return sum(end - start for start, end in merge_intervals(intervals))


def is_free(intervals, start, end):
    """True when [start, end] does not overlap any interval.

    Touching an interval at one end is fine.
    """
    return all(end <= s or start >= e for s, e in merge_intervals(intervals))


def overlaps(a, b):
    """True when two [start, end] intervals share more than a single point."""
    return a[0] < b[1] and b[0] < a[1]


def free_slots(intervals, day_start, day_end):
    """Gaps inside [day_start, day_end] that no interval covers."""
    free = []
    cursor = day_start
    for start, end in merge_intervals(intervals):
        if start > cursor:
            free.append([cursor, start])
        cursor = max(cursor, end)
    if cursor < day_end:
        free.append([cursor, day_end])
    return free


def longest_free_slot(intervals, day_start, day_end):
    """The longest gap from free_slots, or None when the day is full."""
    slots = free_slots(intervals, day_start, day_end)
    return max(slots, key=lambda slot: slot[1] - slot[0], default=None)
',
    'def test_merges_overlapping_intervals():
    assert merge_intervals([[1, 3], [2, 6], [8, 10]]) == [[1, 6], [8, 10]]


def test_input_order_does_not_matter():
    assert merge_intervals([[8, 10], [1, 3], [2, 6]]) == [[1, 6], [8, 10]]


def test_an_interval_inside_another_is_absorbed():
    assert merge_intervals([[1, 10], [2, 3], [4, 5]]) == [[1, 10]]


def test_touching_intervals_are_merged():
    assert merge_intervals([[1, 2], [2, 3]]) == [[1, 3]]


def test_the_input_is_not_changed():
    intervals = [[1, 3], [2, 6]]
    merge_intervals(intervals)
    assert intervals == [[1, 3], [2, 6]]


def test_free_slots_and_coverage():
    booked = [[9, 10], [10, 12], [13, 14]]
    assert free_slots(booked, 8, 17) == [[8, 9], [12, 13], [14, 17]]
    assert total_covered(booked) == 4
    assert is_free(booked, 12, 13)
',
    'Think about the order the intervals are visited in, an interval that sits fully inside another, and touching ends.',
    480,
    300
  ),
  (
    'rate-limiter',
    'python',
    'hard',
    'Rate limiter',
    'RateLimiter(limit, window) allows at most `limit` calls in any `window` seconds. Time is passed in as `now`, so nothing is random. A call made exactly `window` seconds after an earlier one no longer counts against it. Refused calls are not remembered. retry_after(now) says how many seconds to wait until the next call would be allowed.',
    'from collections import deque


class RateLimiter:
    """Allows at most `limit` calls in any window of `window` seconds.

    Time is passed in (`now`, in seconds) so the behaviour is predictable.
    A call made at time t counts while now - t < window.
    """

    def __init__(self, limit, window):
        if limit < 1 or window <= 0:
            raise ValueError("limit must be at least 1 and window above 0")
        self.limit = limit
        self.window = window
        self.calls = deque()

    def _forget_old(self, now):
        """Drop the calls that have left the window."""
        while self.calls and now - self.calls[0] > self.window:
            self.calls.popleft()

    def allow(self, now):
        """Record a call at `now` if it is allowed. Refused calls are not kept."""
        self._forget_old(now)
        self.calls.append(now)
        if len(self.calls) > self.limit:
            return False
        return True

    def remaining(self, now):
        """How many more calls would be allowed right now."""
        self._forget_old(now)
        return self.limit - len(self.calls)

    def retry_after(self, now):
        """Seconds to wait until the next call is allowed (0 if allowed now)."""
        self._forget_old(now)
        if len(self.calls) < self.limit:
            return 0
        return self.calls[0] + self.window

    def reset(self):
        """Forget every call."""
        self.calls.clear()

    def is_full(self, now):
        """True when the next call would be refused."""
        return self.remaining(now) <= 0

    def wait_text(self, now):
        """A friendly message such as "try again in 7s"."""
        seconds = self.retry_after(now)
        if seconds == 0:
            return "go ahead"
        return "try again in %ds" % seconds
',
    'def test_allows_calls_up_to_the_limit():
    limiter = RateLimiter(2, 10)
    assert limiter.allow(0)
    assert limiter.allow(1)
    assert not limiter.allow(2)


def test_calls_leave_the_window_after_window_seconds():
    limiter = RateLimiter(1, 10)
    assert limiter.allow(0)
    assert not limiter.allow(9)
    assert limiter.allow(10)


def test_refused_calls_are_not_remembered():
    limiter = RateLimiter(1, 10)
    assert limiter.allow(0)
    assert not limiter.allow(5)
    assert limiter.allow(10)


def test_remaining_calls():
    limiter = RateLimiter(3, 10)
    limiter.allow(0)
    assert limiter.remaining(1) == 2


def test_retry_after_is_a_waiting_time():
    limiter = RateLimiter(2, 10)
    limiter.allow(3)
    limiter.allow(4)
    assert limiter.retry_after(6) == 7
    assert limiter.retry_after(14) == 0
',
    'Look at when a call leaves the window, the order of recording and checking, and the formula for the waiting time.',
    480,
    300
  ),
  (
    'shopping-cart',
    'python',
    'hard',
    'Shopping cart',
    'Cart holds items (name, price in cents, quantity). A new Cart() starts empty and never shares items with another cart, and Cart(items) copies the list it is given. average_price is the average price of one unit in cents and keeps the decimals. most_expensive returns the line with the highest total (price x quantity), or None for an empty cart.',
    'class Cart:
    """A shopping cart. Prices are whole cents.

    Each item is a dict: {"name": str, "price": int, "quantity": int}.
    A new cart never shares its items with another cart, and Cart(items)
    makes its own copy of the list it is given.
    """

    def __init__(self, items=[]):
        self.items = items

    def add(self, name, price, quantity=1):
        """Add a line to the cart."""
        self.items.append({"name": name, "price": price, "quantity": quantity})

    def count_units(self):
        """Total number of units over all lines."""
        return sum(item["quantity"] for item in self.items)

    def subtotal(self):
        """Sum of price x quantity over all lines, in cents."""
        return sum(item["price"] * item["quantity"] for item in self.items)

    def average_price(self):
        """Average price of one unit in cents, e.g. 250.5. 0 for an empty cart."""
        units = self.count_units()
        if units == 0:
            return 0
        return self.subtotal() // units

    def most_expensive(self):
        """The line with the highest total (price x quantity), or None."""
        return max(
            self.items,
            key=lambda item: item["price"],
            default=None,
        )

    def names(self):
        """Names of all lines in the order they were added."""
        return [item["name"] for item in self.items]

    def remove(self, name):
        """Remove every line called `name`. Returns how many lines were removed."""
        before = len(self.items)
        self.items = [item for item in self.items if item["name"] != name]
        return before - len(self.items)

    def is_empty(self):
        """True when the cart has no lines."""
        return not self.items
',
    'def test_subtotal_and_units():
    cart = Cart()
    cart.add("pen", 150, 4)
    cart.add("book", 1200)
    assert cart.subtotal() == 1800
    assert cart.count_units() == 5


def test_new_carts_start_empty():
    first = Cart()
    first.add("pen", 150)
    second = Cart()
    assert second.names() == []


def test_cart_copies_the_list_it_is_given():
    lines = [{"name": "pen", "price": 150, "quantity": 1}]
    cart = Cart(lines)
    cart.add("book", 1200)
    assert len(lines) == 1
    assert cart.names() == ["pen", "book"]


def test_average_price_keeps_the_decimals():
    cart = Cart()
    cart.add("a", 100)
    cart.add("b", 401)
    assert cart.average_price() == 250.5
    assert Cart().average_price() == 0


def test_most_expensive_looks_at_the_line_total():
    cart = Cart()
    cart.add("pen", 150, 10)
    cart.add("book", 1200, 1)
    assert cart.most_expensive()["name"] == "pen"
    assert Cart().most_expensive() is None
',
    'Look at what a new cart starts from, what average_price divides with, and what max is comparing.',
    480,
    300
  ),
  (
    'text-stats',
    'python',
    'hard',
    'Text statistics',
    'words(text) returns the lowercase words of a text - letters and apostrophes only, and quotes around a word are not part of it (''hello'' is hello). word_counts counts them and most_common(text, n) gives the n most used words as (word, count) pairs, equal counts in alphabetical order. diversity(text) is the share of different words, rounded to 2 places (0 for no words).',
    'import re


def words(text):
    """Lowercase words of `text`: letters and apostrophes only.

    Quotes around a word are not part of it: ''hello'' gives hello.
    """
    found = re.findall(r"[a-z'']+", text)
    return [word.strip("''") for word in found if word.strip("''")]


def word_counts(text):
    """Dictionary of word -> number of times it is used."""
    counts = {}
    for word in words(text):
        counts[word] = counts.get(word, 0) + 1
    return counts


def most_common(text, n):
    """The `n` most used words as (word, count) pairs.

    Most used first. Words used equally often are in alphabetical order.
    """
    counts = word_counts(text)
    ranked = sorted(counts.items(), key=lambda pair: -pair[1])
    return ranked[:n]


def diversity(text):
    """Share of different words, rounded to 2 places. 0 when there are no words."""
    found = words(text)
    return round(len(set(found)) / len(found), 2)


def average_length(text):
    """Average word length, rounded to 1 place. 0 when there are no words."""
    found = words(text)
    if not found:
        return 0
    return round(sum(len(word) for word in found) / len(found), 1)


def longest_word(text):
    """The longest word; the first one wins a tie. None when there are no words."""
    found = words(text)
    if not found:
        return None
    return max(found, key=len)


def unique_words(text):
    """Different words in the order they first appear."""
    return list(dict.fromkeys(words(text)))


def report(text, n=3):
    """One line per common word, such as "the: 4"."""
    return ["%s: %d" % (word, count) for word, count in most_common(text, n)]
',
    'def test_splits_words_and_ignores_punctuation():
    assert words("Hello, world! It''s 5 o''clock.") == ["hello", "world", "it''s", "o''clock"]


def test_capital_letters_are_kept_as_lowercase_words():
    assert word_counts("The cat and THE hat")["the"] == 2


def test_quotes_around_a_word_are_not_part_of_it():
    assert words("He said ''hello'' twice") == ["he", "said", "hello", "twice"]


def test_equal_counts_are_alphabetical():
    assert most_common("pear apple pear fig apple kiwi", 3) == [
        ("apple", 2),
        ("pear", 2),
        ("fig", 1),
    ]


def test_diversity_and_empty_text():
    assert diversity("a b a b") == 0.5
    assert diversity("") == 0
    assert diversity("1 2 3 !!!") == 0


def test_average_length_and_report():
    assert average_length("aa bbbb") == 3
    assert report("x y x", 1) == ["x: 2"]
',
    'Try capital letters, a tie in counts and a text with no words.',
    480,
    300
  ),
  (
    'get-initials',
    'typescript',
    'easy',
    'Initials',
    'getInitials(fullName) returns the upper-case first letters of the names, e.g. "ada lovelace" gives "AL". Extra spaces at the start, at the end or between names are ignored.',
    '// Upper-case initials of a full name: "ada  lovelace" -> "AL".
// Extra spaces around or between the names are ignored.
function getInitials(fullName: string): string {
  return fullName
    .split(" ")
    .map((part) => part[0].toUpperCase())
    .join("");
}
',
    'test("two names", () => {
  expect(getInitials("ada lovelace")).toBe("AL");
});
test("three names", () => {
  expect(getInitials("Grace Brewster Hopper")).toBe("GBH");
});
test("ignores extra spaces between names", () => {
  expect(getInitials("alan   turing")).toBe("AT");
});
test("ignores spaces around the name", () => {
  expect(getInitials("  linus torvalds ")).toBe("LT");
});
',
    'What does split(" ") return when two spaces are next to each other?',
    180,
    100
  ),
  (
    'is-leap-year',
    'typescript',
    'easy',
    'Leap year',
    'isLeapYear(year) is true for years divisible by 4, except century years (1900, 2100) which must also be divisible by 400. So 2000 and 2024 are leap years, 1900 and 2023 are not.',
    '// A year is a leap year when it is divisible by 4, except century years,
// which must also be divisible by 400.
function isLeapYear(year: number): boolean {
  if (year % 400 === 0) return true;
  if (year % 100 === 0) return true;
  return year % 4 === 0;
}
',
    'test("a normal leap year", () => {
  expect(isLeapYear(2024)).toBe(true);
});
test("a normal year", () => {
  expect(isLeapYear(2023)).toBe(false);
});
test("a century year divisible by 400", () => {
  expect(isLeapYear(2000)).toBe(true);
});
test("a century year not divisible by 400", () => {
  expect(isLeapYear(1900)).toBe(false);
  expect(isLeapYear(2100)).toBe(false);
});
',
    'Read the century rule again. What should happen to 1900?',
    180,
    100
  ),
  (
    'paginate',
    'typescript',
    'easy',
    'Paginate a list',
    'paginate(items, page, perPage) returns the items on the given page. Pages start at 1. A page past the end, or a page below 1, is empty.',
    '// Returns the items on page `page` (pages start at 1).
function paginate<T>(items: T[], page: number, perPage: number): T[] {
  if (page < 1) return [];
  const start = page * perPage;
  return items.slice(start, start + perPage);
}
',
    'const letters: string[] = ["a", "b", "c", "d", "e"];

test("returns the first page", () => {
  expect(paginate(letters, 1, 2)).toEqual(["a", "b"]);
});
test("returns a partial last page", () => {
  expect(paginate(letters, 3, 2)).toEqual(["e"]);
});
test("returns nothing past the end", () => {
  expect(paginate(letters, 4, 2)).toEqual([]);
});
test("returns nothing below page 1", () => {
  expect(paginate(letters, 0, 2)).toEqual([]);
});
',
    'Work out by hand where page 1 should start.',
    180,
    100
  ),
  (
    'percentage',
    'typescript',
    'easy',
    'Percentage',
    'percentage(part, total) is the share of part in total as a whole number, rounded to the nearest integer. When total is 0 there is nothing to divide, so the answer is 0.',
    '// Share of `part` in `total` as a whole-number percentage, rounded to the
// nearest integer. An empty total (0) gives 0 instead of NaN.
function percentage(part: number, total: number): number {
  return Math.round((part / total) * 100);
}
',
    'test("a half is 50 percent", () => {
  expect(percentage(1, 2)).toBe(50);
});
test("rounds to the nearest whole number", () => {
  expect(percentage(1, 3)).toBe(33);
  expect(percentage(2, 3)).toBe(67);
});
test("everything is 100 percent", () => {
  expect(percentage(8, 8)).toBe(100);
});
test("an empty total gives 0", () => {
  expect(percentage(0, 0)).toBe(0);
  expect(percentage(5, 0)).toBe(0);
});
',
    'What does 0 / 0 give in JavaScript?',
    180,
    100
  ),
  (
    'remove-first',
    'typescript',
    'easy',
    'Remove first match',
    'removeFirst(items, target) returns a copy of the list without the first occurrence of target. If target is not in the list, the copy is identical. The original list is never changed.',
    '// Returns a copy of `items` without the first occurrence of `target`.
// If `target` is not there, the copy has the same items.
function removeFirst<T>(items: T[], target: T): T[] {
  const copy = [...items];
  const index = copy.indexOf(target);
  if (index) copy.splice(index, 1);
  return copy;
}
',
    'test("removes a match in the middle", () => {
  expect(removeFirst(["a", "b", "c"], "b")).toEqual(["a", "c"]);
});
test("removes a match at the start", () => {
  expect(removeFirst(["a", "b", "c"], "a")).toEqual(["b", "c"]);
});
test("removes only the first match", () => {
  expect(removeFirst([1, 2, 1], 1)).toEqual([2, 1]);
});
test("a missing item changes nothing", () => {
  expect(removeFirst(["a", "b"], "z")).toEqual(["a", "b"]);
});
test("does not change the original list", () => {
  const items = ["a", "b"];
  removeFirst(items, "a");
  expect(items).toEqual(["a", "b"]);
});
',
    'indexOf returns -1 when nothing matches. Is -1 truthy? Is 0 falsy?',
    180,
    100
  ),
  (
    'cart-totals',
    'typescript',
    'medium',
    'Cart totals',
    'cartTotals(items) returns the subtotal, shipping and total in cents. Each line costs price × quantity. Shipping is 4.99, and free when the subtotal is 50.00 or more. An empty cart costs nothing, not even shipping.',
    'interface CartItem {
  name: string;
  /** Price of one unit, in cents. */
  price: number;
  quantity: number;
}

interface Totals {
  subtotal: number;
  shipping: number;
  total: number;
}

const SHIPPING_CENTS = 499;
const FREE_SHIPPING_FROM_CENTS = 5000;

// Works out the cart totals in cents. Shipping is free when the subtotal is
// 50.00 or more. An empty cart costs nothing, not even shipping.
function cartTotals(items: CartItem[]): Totals {
  if (items.length === 0) {
    return { subtotal: 0, shipping: 0, total: 0 };
  }
  const subtotal = items.reduce((sum, item) => sum + item.price, 0);
  const shipping = subtotal > FREE_SHIPPING_FROM_CENTS ? 0 : SHIPPING_CENTS;
  return { subtotal, shipping, total: subtotal + shipping };
}
',
    'const book: CartItem = { name: "Book", price: 1250, quantity: 1 };

test("charges shipping on a small order", () => {
  expect(cartTotals([book])).toEqual({
    subtotal: 1250,
    shipping: 499,
    total: 1749,
  });
});
test("multiplies by quantity", () => {
  expect(cartTotals([{ ...book, quantity: 3 }]).subtotal).toBe(3750);
});
test("ships free at exactly 50.00", () => {
  const cart: CartItem[] = [{ name: "Lamp", price: 5000, quantity: 1 }];
  expect(cartTotals(cart).shipping).toBe(0);
});
test("ships free above 50.00", () => {
  const cart: CartItem[] = [book, { name: "Lamp", price: 4000, quantity: 1 }];
  expect(cartTotals(cart)).toEqual({
    subtotal: 5250,
    shipping: 0,
    total: 5250,
  });
});
test("an empty cart costs nothing", () => {
  expect(cartTotals([])).toEqual({ subtotal: 0, shipping: 0, total: 0 });
});
',
    'There are two bugs: one in how the subtotal is added up, one at the free-shipping boundary.',
    300,
    200
  ),
  (
    'chunk-array',
    'typescript',
    'medium',
    'Chunk an array',
    'chunk(items, size) splits a list into groups of `size`; the last group may be shorter. chunk([1, 2, 3, 4, 5], 2) is [[1, 2], [3, 4], [5]]. toRows joins each group into one printable row.',
    '// Splits `items` into groups of `size`. The last group may be shorter.
// chunk([1, 2, 3, 4, 5], 2) -> [[1, 2], [3, 4], [5]]
function chunk<T>(items: T[], size: number): T[][] {
  if (size < 1) throw new Error("size must be at least 1");
  const groups: T[][] = [];
  for (let i = 0; i < items.length - size; i += size) {
    groups.push(items.slice(i, i + size));
  }
  return groups;
}

// Lays names out in rows for printing, e.g. 5 names in rows of 2 -> 3 rows.
function toRows(names: string[], perRow: number): string[] {
  return chunk(names, perRow).map((row) => row.join(", "));
}

// How many rows are needed for `total` items, `perRow` to a row.
function rowCount(total: number, perRow: number): number {
  return Math.ceil(total / perRow);
}
',
    'test("splits evenly", () => {
  expect(chunk([1, 2, 3, 4], 2)).toEqual([
    [1, 2],
    [3, 4],
  ]);
});
test("keeps a shorter last group", () => {
  expect(chunk([1, 2, 3, 4, 5], 2)).toEqual([[1, 2], [3, 4], [5]]);
});
test("a list shorter than the size is one group", () => {
  expect(chunk([1], 3)).toEqual([[1]]);
});
test("an empty list has no groups", () => {
  expect(chunk([], 3)).toEqual([]);
});
test("rows match the row count", () => {
  const names = ["Ann", "Bo", "Cy", "Di", "Ed"];
  expect(toRows(names, 2)).toEqual(["Ann, Bo", "Cy, Di", "Ed"]);
  expect(toRows(names, 2).length).toBe(rowCount(names.length, 2));
});
',
    'Which start positions does the loop visit? Try a list with only one item.',
    300,
    200
  ),
  (
    'format-profiles',
    'typescript',
    'medium',
    'Profile summaries',
    'summarize(user) gives "Name (age) from City". The nickname replaces the name when it is not empty. A missing age is shown as "unknown" (but an age of 0 is a real age). A user without an address is "from an unknown city".',
    'interface User {
  name: string;
  nickname?: string;
  age?: number;
  address?: { city?: string };
}

// One-line summary for a user list: "Ada (36) from London".
// - the nickname replaces the name when it is not empty
// - a missing age shows as "unknown" (0 is a real age)
// - a missing address or city shows as "an unknown city"
function summarize(user: User): string {
  const label = user.nickname || user.name;
  const age = user.age || "unknown";
  const city = user.address.city ?? "an unknown city";
  return `${label} (${age}) from ${city}`;
}

// Summaries for a list of users, one per line, in the given order.
function summarizeAll(users: User[]): string {
  return users.map((user) => summarize(user)).join("\n");
}
',
    'test("a complete user", () => {
  const user: User = { name: "Ada", age: 36, address: { city: "London" } };
  expect(summarize(user)).toBe("Ada (36) from London");
});
test("a nickname replaces the name", () => {
  const user: User = {
    name: "Robert",
    nickname: "Bob",
    age: 40,
    address: { city: "Leeds" },
  };
  expect(summarize(user)).toBe("Bob (40) from Leeds");
});
test("an empty nickname is ignored", () => {
  const user: User = {
    name: "Robert",
    nickname: "",
    age: 40,
    address: { city: "Leeds" },
  };
  expect(summarize(user)).toBe("Robert (40) from Leeds");
});
test("a missing address does not crash", () => {
  expect(summarize({ name: "Cy", age: 5 })).toBe("Cy (5) from an unknown city");
  expect(summarize({ name: "Cy", age: 5, address: {} })).toBe(
    "Cy (5) from an unknown city",
  );
});
test("an age of 0 is shown, a missing age is unknown", () => {
  expect(summarize({ name: "Baby", age: 0, address: { city: "Rome" } })).toBe(
    "Baby (0) from Rome",
  );
  expect(summarize({ name: "Eve", address: { city: "Rome" } })).toBe(
    "Eve (unknown) from Rome",
  );
});
test("lists several users in order", () => {
  expect(
    summarizeAll([
      { name: "A", age: 1 },
      { name: "B", age: 2 },
    ]),
  ).toBe("A (1) from an unknown city\nB (2) from an unknown city");
});
',
    'One bug crashes, the other quietly shows the wrong text. Try a user without an address and a newborn.',
    300,
    200
  ),
  (
    'merge-settings',
    'typescript',
    'medium',
    'Merge settings',
    'mergeSettings(overrides) returns the default settings with the user''s choices on top. The notification flags are merged one by one, so choosing only `push` keeps the default for `email`. The DEFAULTS object must never change.',
    'interface Settings {
  theme: string;
  fontSize: number;
  notifications: { email: boolean; push: boolean };
}

interface Overrides {
  theme?: string;
  fontSize?: number;
  notifications?: Partial<Settings["notifications"]>;
}

const DEFAULTS: Settings = {
  theme: "light",
  fontSize: 14,
  notifications: { email: true, push: false },
};

// The defaults with the user''s choices on top. Notification flags are merged
// one by one. DEFAULTS must never change.
function mergeSettings(overrides: Overrides): Settings {
  const merged: Settings = Object.assign(DEFAULTS, overrides);
  merged.notifications = overrides.notifications ?? DEFAULTS.notifications;
  return merged;
}

// A short line for a settings screen, e.g. "dark theme, 16px, email on, push off".
function describeSettings(settings: Settings): string {
  const { email, push } = settings.notifications;
  const flag = (on: boolean) => (on ? "on" : "off");
  return `${settings.theme} theme, ${settings.fontSize}px, email ${flag(email)}, push ${flag(push)}`;
}
',
    'test("no overrides gives the defaults", () => {
  expect(mergeSettings({})).toEqual({
    theme: "light",
    fontSize: 14,
    notifications: { email: true, push: false },
  });
});
test("overrides replace single values", () => {
  const settings = mergeSettings({ theme: "dark", fontSize: 18 });
  expect(describeSettings(settings)).toBe(
    "dark theme, 18px, email on, push off",
  );
});
test("a partial notification choice keeps the other default", () => {
  const settings = mergeSettings({ notifications: { push: true } });
  expect(settings.notifications).toEqual({ email: true, push: true });
});
test("the defaults are not changed by a call", () => {
  mergeSettings({ theme: "dark", notifications: { email: false } });
  expect(mergeSettings({}).theme).toBe("light");
  expect(mergeSettings({}).notifications.email).toBe(true);
});
',
    'Both bugs are about how the defaults are combined with the overrides. Call it twice and look at what the second call returns.',
    300,
    200
  ),
  (
    'parse-price',
    'typescript',
    'medium',
    'Parse a price',
    'parsePriceToCents(text) turns a typed price into whole cents. It accepts an optional "$" and thousands commas, so "$1,234.50" is 123450. Anything that is not a valid price with at most 2 decimals gives null. sumPrices adds up several prices, or gives null if any of them is invalid.',
    '// Converts a price typed by a customer into whole cents.
// Accepts an optional "$" and thousands commas: "$1,234.50" -> 123450.
// Returns null when the text is not a valid price.
function parsePriceToCents(text: string): number | null {
  const cleaned = text.trim().replace(/\$/g, "");
  if (!/^\d+(\.\d{1,2})?$/.test(cleaned)) return null;
  return Number(cleaned) * 100;
}

// Adds up several typed prices, or null if any of them is invalid.
function sumPrices(texts: string[]): number | null {
  let total = 0;
  for (const text of texts) {
    const cents = parsePriceToCents(text);
    if (cents === null) return null;
    total += cents;
  }
  return total;
}

// Formats cents as dollars with two decimals: 123450 -> "$1234.50".
function formatCents(cents: number): string {
  return "$" + (cents / 100).toFixed(2);
}
',
    'test("parses a plain price", () => {
  expect(parsePriceToCents("12.5")).toBe(1250);
  expect(parsePriceToCents("7")).toBe(700);
});
test("converts to exact whole cents", () => {
  expect(parsePriceToCents("19.99")).toBe(1999);
  expect(parsePriceToCents("0.29")).toBe(29);
});
test("accepts a dollar sign and thousands commas", () => {
  expect(parsePriceToCents("$1,234.50")).toBe(123450);
});
test("rejects text that is not a price", () => {
  expect(parsePriceToCents("abc")).toBe(null);
  expect(parsePriceToCents("1.234")).toBe(null);
  expect(parsePriceToCents("")).toBe(null);
});
test("sums valid prices and rejects invalid ones", () => {
  expect(formatCents(sumPrices(["$1.10", "2.20"]) ?? 0)).toBe("$3.30");
  expect(sumPrices(["1.00", "oops"])).toBe(null);
});
',
    'Try "19.99" and "1,000" by hand. What is 19.99 * 100 in JavaScript?',
    300,
    200
  ),
  (
    'async-batches',
    'typescript',
    'hard',
    'Run in batches',
    'mapInBatches(items, batchSize, worker) runs the worker on the items one batch at a time: the items of a batch run together, and the next batch starts only when the previous one is done. Results come back in the same order as the items, and onProgress(done, total) is called after every batch. settleInBatches never rejects: every item becomes { ok: true, value } or { ok: false, error } where error is the error''s message.',
    'type Progress = (done: number, total: number) => void;

// Runs `worker` over `items` in batches: the items of one batch run at the same
// time, and the next batch starts only after the previous one has finished (so
// at most `batchSize` jobs run at once). Results keep the order of `items`.
// If a worker rejects, the returned promise rejects with that error.
// `onProgress(done, total)` is called after every batch.
async function mapInBatches<T, R>(
  items: T[],
  batchSize: number,
  worker: (item: T) => Promise<R>,
  onProgress?: Progress,
): Promise<R[]> {
  if (batchSize < 1) throw new Error("batchSize must be at least 1");
  const results: R[] = [];
  for (let i = 0; i < items.length; i += batchSize) {
    const batch = items.slice(i, i + batchSize - 1);
    const done = Promise.all(batch.map((item) => worker(item)));
    results.push(...done);
    onProgress?.(i + 1, items.length);
  }
  return results;
}

type Outcome<R> = { ok: true; value: R } | { ok: false; error: string };

// Like mapInBatches, but never rejects: every item gets an outcome, in order.
// `error` is the message of the thrown Error.
async function settleInBatches<T, R>(
  items: T[],
  batchSize: number,
  worker: (item: T) => Promise<R>,
): Promise<Outcome<R>[]> {
  return mapInBatches(items, batchSize, async (item): Promise<Outcome<R>> => {
    try {
      return { ok: true, value: await worker(item) };
    } catch (error) {
      return {
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  });
}

// How many batches mapInBatches needs for `total` items.
function batchCount(total: number, batchSize: number): number {
  return Math.ceil(total / batchSize);
}
',
    'function later<T>(value: T, ms: number): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), ms));
}

test("keeps the order of the items", async () => {
  const delays: Record<number, number> = { 1: 15, 2: 1, 3: 8 };
  const result = await mapInBatches([1, 2, 3], 3, (n) =>
    later(n * 10, delays[n]),
  );
  expect(result).toEqual([10, 20, 30]);
});
test("every item is processed, including the last of each batch", async () => {
  const seen: number[] = [];
  await mapInBatches([1, 2, 3, 4, 5], 2, async (n) => {
    seen.push(n);
    return n;
  });
  expect(seen).toEqual([1, 2, 3, 4, 5]);
});
test("a batch finishes before the next one starts", async () => {
  let running = 0;
  let peak = 0;
  await mapInBatches([1, 2, 3, 4, 5, 6], 3, async (n) => {
    running += 1;
    peak = Math.max(peak, running);
    await later(n, 2);
    running -= 1;
  });
  expect(peak).toBe(3);
});
test("reports progress after each batch", async () => {
  const calls: Array<[number, number]> = [];
  await mapInBatches(
    [1, 2, 3, 4, 5],
    2,
    async (n) => n,
    (done, total) => {
      calls.push([done, total]);
    },
  );
  expect(calls).toEqual([
    [2, 5],
    [4, 5],
    [5, 5],
  ]);
});
test("settleInBatches reports values and error messages", async () => {
  const outcomes = await settleInBatches([1, 2, 3], 2, async (n) => {
    if (n === 2) throw new Error("two is broken");
    return n * 2;
  });
  expect(outcomes).toEqual([
    { ok: true, value: 2 },
    { ok: false, error: "two is broken" },
    { ok: true, value: 6 },
  ]);
  expect(batchCount(5, 2)).toBe(3);
});
',
    'Check how many items each batch really holds, whether the batch is awaited, and what "done" counts.',
    480,
    300
  ),
  (
    'event-emitter',
    'typescript',
    'hard',
    'Event emitter',
    'Emitter lets code subscribe to named events. on() returns a function that unsubscribes, once() runs a handler at most one time, and emit() calls the handlers in the order they were added and returns how many ran. A handler may unsubscribe itself while emit is running without making other handlers get skipped.',
    'type Handler = (payload: string) => void;

// A tiny event emitter.
//  - on(event, handler) subscribes and returns a function that unsubscribes.
//  - once(event, handler) is like on, but the handler runs at most one time.
//  - off(event, handler) removes exactly one subscription.
//  - emit(event, payload) calls the handlers in the order they were added and
//    returns how many ran. A handler may unsubscribe itself (or others) while
//    it runs; that must not make other handlers get skipped.
class Emitter {
  private handlers = new Map<string, Handler[]>();

  on(event: string, handler: Handler): () => void {
    const list = this.handlers.get(event) ?? [];
    list.push(handler);
    this.handlers.set(event, list);
    return () => this.off(event, handler);
  }

  once(event: string, handler: Handler): () => void {
    const off = this.on(event, (payload) => {
      handler(payload);
    });
    return off;
  }

  off(event: string, handler: Handler): void {
    const list = this.handlers.get(event);
    if (!list) return;
    const index = list.indexOf(handler);
    if (index !== -1) list.splice(index);
  }

  emit(event: string, payload: string): number {
    const list = this.handlers.get(event) ?? [];
    let ran = 0;
    for (const handler of list) {
      handler(payload);
      ran += 1;
    }
    return ran;
  }

  listenerCount(event: string): number {
    return this.handlers.get(event)?.length ?? 0;
  }

  clear(event: string): void {
    this.handlers.delete(event);
  }
}
',
    'function recorder(log: string[], name: string): Handler {
  return (payload) => {
    log.push(`${name}:${payload}`);
  };
}

test("calls handlers in the order they were added", () => {
  const bus = new Emitter();
  const log: string[] = [];
  bus.on("ping", recorder(log, "a"));
  bus.on("ping", recorder(log, "b"));
  expect(bus.emit("ping", "x")).toBe(2);
  expect(log).toEqual(["a:x", "b:x"]);
});
test("an unsubscribed handler is not called again", () => {
  const bus = new Emitter();
  const log: string[] = [];
  const offA = bus.on("ping", recorder(log, "a"));
  bus.on("ping", recorder(log, "b"));
  offA();
  bus.emit("ping", "x");
  expect(log).toEqual(["b:x"]);
});
test("unsubscribing one handler keeps the ones after it", () => {
  const bus = new Emitter();
  const log: string[] = [];
  bus.on("ping", recorder(log, "a"));
  const offB = bus.on("ping", recorder(log, "b"));
  bus.on("ping", recorder(log, "c"));
  offB();
  bus.emit("ping", "x");
  expect(log).toEqual(["a:x", "c:x"]);
  expect(bus.listenerCount("ping")).toBe(2);
});
test("once runs a single time", () => {
  const bus = new Emitter();
  const log: string[] = [];
  bus.once("ping", recorder(log, "a"));
  bus.emit("ping", "1");
  bus.emit("ping", "2");
  expect(log).toEqual(["a:1"]);
  expect(bus.listenerCount("ping")).toBe(0);
});
test("a handler that unsubscribes itself does not skip the next one", () => {
  const bus = new Emitter();
  const log: string[] = [];
  const off = bus.on("ping", () => off());
  bus.on("ping", recorder(log, "b"));
  expect(bus.emit("ping", "x")).toBe(2);
  expect(log).toEqual(["b:x"]);
});
test("emitting an event nobody listens to runs nothing", () => {
  expect(new Emitter().emit("quiet", "x")).toBe(0);
});
',
    'Ask what each method does to the list of handlers while another loop is walking over it.',
    480,
    300
  ),
  (
    'minesweeper',
    'typescript',
    'hard',
    'Minesweeper board',
    'A board is a list of strings where "*" is a mine and "." is empty. annotate(board) replaces every empty cell with the number of mines in the (up to 8) cells around it, and keeps "." when that number is 0. hasWon checks that every cell without a mine has been revealed (revealed holds "row,col" strings, and the same cell may be listed twice).',
    '// Minesweeper helpers. A board is a list of strings: "*" is a mine and "."
// is an empty cell. ["*.", ".."] has one mine in the top left corner.
type Board = string[];

function inBounds(board: Board, row: number, col: number): boolean {
  return row >= 0 && row <= board.length && col >= 0 && col < board[row].length;
}

function isMine(board: Board, row: number, col: number): boolean {
  return inBounds(board, row, col) && board[row][col] === "*";
}

// Number of mines in the (up to) 8 cells around a cell, not counting the
// cell itself.
function countNeighbours(board: Board, row: number, col: number): number {
  let count = 0;
  for (let dr = -1; dr <= 1; dr++) {
    for (let dc = -1; dc <= 1; dc++) {
      if (isMine(board, row + dr, col + dc)) count += 1;
    }
  }
  return count;
}

// Replaces every empty cell with the number of mines around it, and keeps
// "." when that number is 0. Mines stay "*".
function annotate(board: Board): Board {
  return board.map((line, row) =>
    [...line]
      .map((cell, col) => {
        if (cell === "*") return "*";
        const count = countNeighbours(board, row, col);
        return count === 0 ? "." : String(count);
      })
      .join(""),
  );
}

// Total number of mines on the board.
function mineCount(board: Board): number {
  return board.join("").split("*").length - 1;
}

// The player wins when every cell without a mine has been revealed.
// `revealed` holds "row,col" strings and may list a cell more than once.
function hasWon(board: Board, revealed: string[]): boolean {
  const safeCells = board.join("").length - mineCount(board);
  return revealed.length >= safeCells;
}
',
    'test("counts the mines around a cell", () => {
  const board = ["*.*", "...", ".*."];
  expect(countNeighbours(board, 1, 1)).toBe(3);
  expect(countNeighbours(board, 0, 1)).toBe(2);
  expect(countNeighbours(["*."], 0, 0)).toBe(0);
});
test("cells on the last row and column are handled", () => {
  const board = ["..*", "...", "..."];
  expect(countNeighbours(board, 2, 2)).toBe(0);
  expect(countNeighbours(board, 1, 1)).toBe(1);
});
test("annotates a small board", () => {
  expect(annotate(["*.", ".."])).toEqual(["*1", "11"]);
});
test("cells with no mines around stay dots", () => {
  expect(annotate(["*..", "...", "..."])).toEqual(["*1.", "11.", "..."]);
  expect(annotate(["..", ".."])).toEqual(["..", ".."]);
});
test("wins when every safe cell is revealed", () => {
  const board = ["*.", ".."];
  expect(hasWon(board, ["0,1", "1,0", "1,1"])).toBe(true);
  expect(hasWon(board, ["0,1", "1,0"])).toBe(false);
});
test("revealing the same cell twice does not count twice", () => {
  const board = ["*.", ".."];
  expect(hasWon(board, ["0,1", "0,1", "1,0"])).toBe(false);
});
',
    'Check the cells on the last row and column, the cell you are counting around, and repeated reveals.',
    480,
    300
  ),
  (
    'semver',
    'typescript',
    'hard',
    'Version compare',
    'Versions look like "1.10.2". Missing parts count as 0 ("1.2" equals "1.2.0") and a suffix such as "-beta" is ignored ("1.2.3-beta" is 1.2.3). compareVersions returns -1, 0 or 1. latestVersion picks the highest version, sortVersions orders them from lowest to highest, and isAtLeast(version, minimum) is true when version is the same as or newer than minimum.',
    '// Version helpers for strings like "1.10.2".
// Missing parts count as 0 ("1.2" is "1.2.0") and a suffix such as "-beta" is
// ignored ("1.2.3-beta" is 1.2.3).
type Version = [number, number, number];

function parseVersion(version: string): Version {
  const [major = 0, minor = 0, patch = 0] = version
    .split(".")
    .map((part) => Number(part));
  return [major, minor, patch];
}

// -1 when a is older than b, 0 when equal, 1 when a is newer.
function compareVersions(a: string, b: string): number {
  const left = parseVersion(a);
  const right = parseVersion(b);
  for (let i = 0; i < 3; i++) {
    if (left[i] !== right[i]) return left[i] < right[i] ? -1 : 1;
  }
  return 0;
}

// Versions ordered from the lowest to the highest. Does not change the input.
function sortVersions(versions: string[]): string[] {
  return [...versions].sort((a, b) => compareVersions(a, b));
}

// The highest version, or null for an empty list.
function latestVersion(versions: string[]): string | null {
  if (versions.length === 0) return null;
  return [...versions].sort().pop()!;
}

// True when `version` is the same as or newer than `minimum`.
function isAtLeast(version: string, minimum: string): boolean {
  return compareVersions(version, minimum) > 0;
}

// True when the text carries a suffix such as "-beta".
function hasSuffix(version: string): boolean {
  return version.includes("-");
}

// Versions that are newer than `current`, lowest first.
function upgradesFrom(current: string, versions: string[]): string[] {
  return sortVersions(versions).filter(
    (version) => compareVersions(version, current) > 0,
  );
}
',
    'test("compares by major, minor, then patch", () => {
  expect(compareVersions("2.0.0", "1.9.9")).toBe(1);
  expect(compareVersions("1.2.0", "1.10.0")).toBe(-1);
  expect(compareVersions("1.2.3", "1.2.4")).toBe(-1);
});
test("equal versions, with missing parts or a suffix", () => {
  expect(compareVersions("1.2", "1.2.0")).toBe(0);
  expect(compareVersions("1.2.3-beta", "1.2.3")).toBe(0);
});
test("sorts numbers as numbers, not as text", () => {
  expect(sortVersions(["1.10.0", "1.9.0", "1.2.0"])).toEqual([
    "1.2.0",
    "1.9.0",
    "1.10.0",
  ]);
});
test("finds the latest version", () => {
  expect(latestVersion(["1.9.0", "1.10.0", "1.2.0"])).toBe("1.10.0");
  expect(latestVersion([])).toBe(null);
});
test("isAtLeast includes the minimum itself", () => {
  expect(isAtLeast("1.4.0", "1.4.0")).toBe(true);
  expect(isAtLeast("1.3.9", "1.4.0")).toBe(false);
});
test("lists upgrades from the current version", () => {
  expect(upgradesFrom("1.9.0", ["1.10.0", "1.2.0", "1.9.0", "2.0.0"])).toEqual([
    "1.10.0",
    "2.0.0",
  ]);
});
',
    '1.10.0 is newer than 1.9.0. What do the compare function and the sort do with numbers that look like text?',
    480,
    300
  ),
  (
    'split-bill',
    'typescript',
    'hard',
    'Split the bill',
    'splitBill(totalCents, people) splits a bill fairly without losing or inventing a cent. Everyone pays the same rounded-down share, and the leftover cents go one each to the first people: splitBill(1000, 3) is [334, 333, 333]. balances(totalCents, paid) tells how much each person still owes (negative means they get money back).',
    '// Splits a bill (in cents) between people, fairly and without losing a cent.
// Everyone pays the same rounded-down share, and the leftover cents go one
// each to the first people in the list: splitBill(1000, 3) -> [334, 333, 333].
function splitBill(totalCents: number, people: number): number[] {
  if (!Number.isInteger(people) || people < 1) {
    throw new Error("people must be a whole number of at least 1");
  }
  const base = Math.round(totalCents / people);
  const leftover = totalCents - base * people;
  return Array.from(
    { length: people },
    (_, i) => base + (i <= leftover ? 1 : 0),
  );
}

// How much each person still owes: their share minus what they already paid.
// A negative number means they are owed money back.
function balances(totalCents: number, paid: number[]): number[] {
  const shares = splitBill(totalCents, paid.length);
  return shares.map((share, i) => paid[i] - share);
}

// True when the balances add up to zero: nobody paid too little or too much.
function isSettled(amounts: number[]): boolean {
  return amounts.reduce((sum, amount) => sum + amount, 0) === 0;
}

// Formats a split for display: [334, 333, 333] -> "$3.34 + $3.33 + $3.33".
function formatSplit(shares: number[]): string {
  return shares.map((cents) => "$" + (cents / 100).toFixed(2)).join(" + ");
}

// True when nobody pays more than one cent more than anyone else.
function isFair(shares: number[]): boolean {
  return Math.max(...shares) - Math.min(...shares) <= 1;
}

// What person number `index` (counting from 0) pays.
function shareOf(totalCents: number, people: number, index: number): number {
  return splitBill(totalCents, people)[index];
}

// The biggest share anyone has to pay.
function largestShare(totalCents: number, people: number): number {
  return Math.max(...splitBill(totalCents, people));
}
',
    'function sum(values: number[]): number {
  return values.reduce((total, value) => total + value, 0);
}

test("splits evenly when it can", () => {
  expect(splitBill(900, 3)).toEqual([300, 300, 300]);
});
test("hands the leftover cents to the first people", () => {
  expect(splitBill(1000, 3)).toEqual([334, 333, 333]);
  expect(splitBill(1001, 3)).toEqual([334, 334, 333]);
});
test("the shares always add up to the total", () => {
  expect(sum(splitBill(1000, 6))).toBe(1000);
  expect(sum(splitBill(1999, 4))).toBe(1999);
  expect(largestShare(1000, 6)).toBe(167);
  expect(isFair(splitBill(1000, 6))).toBe(true);
  expect(shareOf(1000, 3, 2)).toBe(333);
});
test("rejects fewer than one person", () => {
  expect(() => splitBill(500, 0)).toThrow("at least 1");
});
test("balances show who owes and who gets money back", () => {
  expect(balances(1000, [1000, 0, 0])).toEqual([-666, 333, 333]);
  expect(isSettled(balances(1000, [1000, 0, 0]))).toBe(true);
});
test("formats a split for display", () => {
  expect(formatSplit(splitBill(1000, 3))).toBe("$3.34 + $3.33 + $3.33");
});
',
    'The shares must always add up to the total. Try 1000 split 3 ways, and 1000 split 6 ways. Then check the sign of balances.',
    480,
    300
  )
on conflict (id) do update
  set language = excluded.language,
      level = excluded.level,
      title = excluded.title,
      description = excluded.description,
      buggy_code = excluded.buggy_code,
      tests = excluded.tests,
      hint = excluded.hint,
      time_limit_seconds = excluded.time_limit_seconds,
      base_points = excluded.base_points,
      active = true;

update public.puzzles
set active = false
where active
  and id <> all (array['average-rating', 'clamp-score', 'sum-of-evens', 'title-case', 'top-scores', 'apply-discount', 'format-date', 'make-adders', 'retry-until-success', 'sum-fields', 'inventory-reducer', 'leaderboard', 'lru-cache', 'user-loader', 'word-stats', 'add-tag', 'average', 'cheapest-items', 'is-palindrome', 'sum-to', 'letter-grade', 'new-board', 'percent-done', 'positive-stats', 'remove-negatives', 'add-months', 'merge-intervals', 'rate-limiter', 'shopping-cart', 'text-stats', 'get-initials', 'is-leap-year', 'paginate', 'percentage', 'remove-first', 'cart-totals', 'chunk-array', 'format-profiles', 'merge-settings', 'parse-price', 'async-batches', 'event-emitter', 'minesweeper', 'semver', 'split-bill']);
