import type { PuzzleSource } from "./load";
import { PUZZLE_LEVELS } from "./schema";

/**
 * The puzzle catalog the round engine picks from, as SQL. Seeded locally
 * (supabase/config.toml) and run in the SQL Editor on the live project
 * whenever puzzles/ changes. Never contains `fix.*`.
 */
export const PUZZLE_CATALOG_FILE = "supabase/puzzles.sql";

/** A SQL string literal (standard_conforming_strings is on in Postgres). */
function literal(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function compare(a: PuzzleSource, b: PuzzleSource): number {
  return (
    a.meta.language.localeCompare(b.meta.language) ||
    PUZZLE_LEVELS.indexOf(a.meta.level) - PUZZLE_LEVELS.indexOf(b.meta.level) ||
    a.meta.id.localeCompare(b.meta.id)
  );
}

function row({ meta, buggy, tests }: PuzzleSource): string {
  const values = [
    literal(meta.id),
    literal(meta.language),
    literal(meta.level),
    literal(meta.title),
    literal(meta.description),
    literal(buggy),
    literal(tests),
    literal(meta.hint),
    String(meta.timeLimitSec),
    String(meta.basePoints),
  ];
  return `  (\n    ${values.join(",\n    ")}\n  )`;
}

/**
 * Upserts every puzzle and retires (`active = false`) the ones no longer in
 * puzzles/, so running it again is always safe.
 */
export function renderPuzzleCatalogSql(puzzles: PuzzleSource[]): string {
  const sorted = [...puzzles].sort(compare);
  const ids = sorted.map((puzzle) => literal(puzzle.meta.id)).join(", ");
  return `-- Generated by \`pnpm puzzles:build\` from puzzles/. Do not edit.
--
-- The puzzle catalog that race rounds pick from. Reference fixes are left out
-- on purpose: they never go in the database. Safe to run again: adds new
-- puzzles, updates changed ones and retires the ones no longer in puzzles/
-- (kept for old rounds, never picked again).
--
-- Local: the seed file, applied by \`pnpm db:reset\`. Live: run in the
-- Supabase SQL Editor after migration 20261008000006, and again whenever
-- puzzles/ changes.

insert into public.puzzles
  (id, language, level, title, description, buggy_code, tests, hint, time_limit_seconds, base_points)
values
${sorted.map(row).join(",\n")}
on conflict (id) do update
  set language = excluded.language,
      level = excluded.level,
      title = excluded.title,
      description = excluded.description,
      buggy_code = excluded.buggy_code,
      tests = excluded.tests,
      hint = excluded.hint,
      time_limit_seconds = excluded.time_limit_seconds,
      base_points = excluded.base_points,
      active = true;

update public.puzzles
set active = false
where active
  and id <> all (array[${ids}]);
`;
}
