import { format, resolveConfig } from "prettier";
import type { PuzzleSource } from "./load";

/**
 * The reference fixes, for the fix reveal after a round ends
 * (app/api/rounds/[roundId]/fix). `import "server-only"` makes the build fail
 * if client code ever imports it; `pnpm fixes:check` scans the built client
 * chunks as well.
 */
export const PUZZLE_FIXES_FILE = "lib/puzzles/generated/fixes.ts";

/** Source of `PUZZLE_FIXES_FILE`, formatted with the repo's Prettier config. */
export async function renderPuzzleFixes(
  puzzles: PuzzleSource[],
  filepath: string,
): Promise<string> {
  const fixes = Object.fromEntries(
    [...puzzles]
      .sort((a, b) => a.meta.id.localeCompare(b.meta.id))
      .map(({ meta, fix }) => [meta.id, fix]),
  );
  const source = `// Generated by \`pnpm puzzles:build\` from puzzles/. Do not edit.
// Reference fixes by puzzle id. Server only: players get one only through
// the fix reveal route, after the round has ended.
import "server-only";

export const PUZZLE_FIXES: Readonly<Record<string, string>> = ${JSON.stringify(fixes, null, 2)};
`;
  const config = await resolveConfig(filepath);
  return format(source, { ...config, filepath });
}
