import { format, resolveConfig } from "prettier";
import type { PuzzleSource } from "./load";
import { PUZZLE_LEVELS, type PublicPuzzle } from "./schema";

/** The generated module the app imports. Never contains `fix.*`. */
export const PUZZLE_INDEX_FILE = "lib/puzzles/generated/index.ts";

/** Drops the reference fix. The only way puzzle data reaches the app. */
export function toPublicPuzzle({
  meta,
  buggy,
  tests,
}: PuzzleSource): PublicPuzzle {
  return { ...meta, buggy, tests };
}

function compare(a: PublicPuzzle, b: PublicPuzzle): number {
  return (
    a.language.localeCompare(b.language) ||
    PUZZLE_LEVELS.indexOf(a.level) - PUZZLE_LEVELS.indexOf(b.level) ||
    a.id.localeCompare(b.id)
  );
}

/** Source of `PUZZLE_INDEX_FILE`, formatted with the repo's Prettier config. */
export async function renderPuzzleIndex(
  puzzles: PuzzleSource[],
  filepath: string,
): Promise<string> {
  const list = puzzles.map(toPublicPuzzle).sort(compare);
  const source = `// Generated by \`pnpm puzzles:build\` from puzzles/. Do not edit.
// Reference fixes are left out on purpose: players must never receive them.
import type { PublicPuzzle } from "@/lib/puzzles/schema";

export const PUZZLES: readonly PublicPuzzle[] = ${JSON.stringify(list, null, 2)};
`;
  const config = await resolveConfig(filepath);
  return format(source, { ...config, filepath });
}
